name: Merge or Pull requests

on:
  workflow_dispatch:
  push:
    branches:
      - 'dev'
      - 'next'
  pull_request:

concurrency: 
  group: ${{ github.sha }}
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Artifact
        run: |
          ruby build.rb --install-gdc
          ruby build.rb --install-ldc
          ruby build.rb test --run-test
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          path: "upload/*"
