# https://github.com/dlang/dub/blob/master/.github/workflows/main.yml
# https://github.com/dlang-community/setup-dlang/blob/v1/.github/workflows/test.yml
name: Build with other DC

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'
    branches:
      - 'dev'
      - 'next'

concurrency: 
  group: ${{ github.workflow }}-${{ github.sha }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        dc:
          - dmd-latest
          - ldc-latest

    runs-on: ${{ matrix.os }}
    steps:
      - name: Prepare compiler
        uses: dlang-community/setup-dlang@v1
        with:
          compiler: ${{ matrix.dc }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: '[POSIX] Build'
        if: runner.os != 'Windows'
        run: |
          dub build --compiler=$DC -b release
          mkdir -p upload
          mv d-demo upload/x86-64_${{ matrix.os }}_${{ matrix.dc }}
      - name: '[Windows] Build'
        if: runner.os == 'Windows'
        run: |
          dub build --compiler=$DC -b release
          mkdir -p upload
          mv d-demo upload/x86-64_${{ matrix.os }}_${{ matrix.dc }}
        shell: bash
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: x86-64_${{ matrix.os }}_${{ matrix.dc }}
          path: "upload/*"
      - name: Upload to Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: "upload/*"